import type { GisLayerDefinition } from "../types/gis";

export const defaultGisLayers: GisLayerDefinition[] = [
  {
    id: "basemap",
    title: "OpenStreetMap",
    kind: "basemap",
    group: "base-maps",
    visible: true,
    locked: true,
    opacity: 0.55,
    order: 10,
    selectable: false,
    editable: false,
    removable: false,
    exportable: false,
    sourceName: "OpenStreetMap",
    security: "UNCLASSIFIED",
  },
  {
    id: "control-measures",
    title: "Operational Control Measures",
    kind: "vector",
    group: "control-measures",
    visible: true,
    locked: false,
    opacity: 1,
    order: 20,
    selectable: true,
    editable: true,
    removable: false,
    exportable: true,
    featureCount: 3,
    security: "RESTRICTED",
  },
  {
    id: "blue-units",
    title: "BLUEFOR Units",
    kind: "vector",
    group: "friendly",
    visible: true,
    locked: false,
    opacity: 1,
    order: 30,
    selectable: true,
    editable: false,
    removable: false,
    exportable: true,
    featureCount: 3,
    security: "RESTRICTED",
  },
  {
    id: "red-units",
    title: "REDFOR Units",
    kind: "vector",
    group: "enemy",
    visible: true,
    locked: false,
    opacity: 1,
    order: 40,
    selectable: true,
    editable: false,
    removable: false,
    exportable: true,
    featureCount: 2,
    security: "RESTRICTED",
  },
  {
    id: "user-graphics",
    title: "User Tactical Graphics",
    kind: "vector",
    group: "user",
    visible: true,
    locked: false,
    opacity: 1,
    order: 50,
    selectable: true,
    editable: true,
    removable: false,
    exportable: true,
    featureCount: 0,
    security: "RESTRICTED",
  },
];
