import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { NavLink, Route, Routes } from "react-router-dom";
import { useAuth } from "./auth/AuthContext";
import ProtectedRoute from "./auth/ProtectedRoute";
import LoginPage from "./pages/LoginPage";
import { api } from "./services/api";
import "./App.css";

const navItems = [
  ["dashboard", "/"],
  ["projects", "/projects"],
  ["map", "/map"],
  ["operations", "/operations"],
  ["reports", "/reports"],
  ["administration", "/administration"]
];

function Placeholder({ title }) {
  return (
    <section className="panel">
      <h2>{title}</h2>
      <p>This module will be generated by the ODIN Builder.</p>
    </section>
  );
}

function Dashboard() {
  const { t } = useTranslation();
  const [health, setHealth] = useState({
    backend: "checking",
    database: "checking"
  });

  useEffect(() => {
    api.get("/health")
      .then(({ data }) => {
        setHealth({
          backend: data.status === "ok" ? "ready" : "unavailable",
          database: data.database === "connected" ? "ready" : "unavailable"
        });
      })
      .catch(() => {
        setHealth({ backend: "unavailable", database: "unavailable" });
      });
  }, []);

  return (
    <>
      <section className="hero">
        <div>
          <span className="eyebrow">ODIN WEB V3</span>
          <h1>{t("foundationTitle")}</h1>
          <p>{t("foundationText")}</p>
        </div>
        <div className="mission-badge">C2</div>
      </section>

      <section className="panel">
        <div className="panel-heading">
          <h2>{t("systemStatus")}</h2>
          <span className="online-dot" />
        </div>
        <div className="status-grid">
          <StatusCard label={t("frontend")} value={t("ready")} />
          <StatusCard
            label={t("backend")}
            value={health.backend === "ready" ? t("ready") : t("unavailable")}
          />
          <StatusCard
            label={t("database")}
            value={health.database === "ready" ? t("ready") : t("unavailable")}
          />
        </div>
      </section>

      <section className="panel next-panel">
        <strong>{t("nextModule")}</strong>
      </section>
    </>
  );
}

function StatusCard({ label, value }) {
  return (
    <article className="status-card">
      <span>{label}</span>
      <strong>{value}</strong>
    </article>
  );
}

function ApplicationShell() {
  const { t, i18n } = useTranslation();
  const { user, logout } = useAuth();

  const changeLanguage = async () => {
    const next = i18n.language === "ar" ? "en" : "ar";
    await i18n.changeLanguage(next);
    localStorage.setItem("odin-language", next);
    document.documentElement.lang = next;
    document.documentElement.dir = next === "ar" ? "rtl" : "ltr";
  };

  const displayName = i18n.language === "ar"
    ? user?.displayNameAr
    : user?.displayNameEn;

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <div className="brand-mark">O</div>
          <div>
            <strong>{t("product")}</strong>
            <small>{t("subtitle")}</small>
          </div>
        </div>

        <nav>
          {navItems.map(([key, path]) => (
            <NavLink key={key} to={path} end={path === "/"}>
              {t(key)}
            </NavLink>
          ))}
        </nav>

        <div className="account-card">
          <small>{t("signedInAs")}</small>
          <strong>{displayName}</strong>
          <span>{user?.role}</span>
        </div>

        <button className="language-button" onClick={changeLanguage}>
          {t("language")}
        </button>
        <button className="logout-button" onClick={logout}>
          {t("logout")}
        </button>
      </aside>

      <main className="content">
        <Routes>
          <Route path="/" element={<Dashboard />} />
          <Route path="/projects" element={<Placeholder title={t("projects")} />} />
          <Route path="/map" element={<Placeholder title={t("map")} />} />
          <Route path="/operations" element={<Placeholder title={t("operations")} />} />
          <Route path="/reports" element={<Placeholder title={t("reports")} />} />
          <Route path="/administration" element={<Placeholder title={t("administration")} />} />
        </Routes>
      </main>
    </div>
  );
}

export default function App() {
  return (
    <Routes>
      <Route path="/login" element={<LoginPage />} />
      <Route
        path="/*"
        element={
          <ProtectedRoute>
            <ApplicationShell />
          </ProtectedRoute>
        }
      />
    </Routes>
  );
}